### ISSUE TITLE
How to use `wasi-vfs` with Python?

### ISSUE THREAD

**Issue by rjzak** [kateinoigakukun/wasi-vfs#5]
I'd like to use `wasi-vfs` with [Python-Wasi](https://github.com/singlestore-labs/python-wasi), as I've done with Ruby, but it seems something has to be done with the .wasm file before `wasi-vfs` can add the files. How can I get started? Thank you.

CC: @nickvidal @bstrie

**Comment by kateinoigakukun** [comment]
I haven't tried it yet but it works well in theory. As shown in the section (https://github.com/kateinoigakukun/wasi-vfs#build-and-run-wasi-application), it would work by just linking `libwasi_vfs.a`, which is distributed in the GitHub Release page (https://github.com/kateinoigakukun/wasi-vfs/releases/tag/v0.1.1)

**Comment by pvetere** [comment]
I was able to successfully build WASI Python with the VFS.  I cloned tiran's cpython fork (https://github.com/tiran/cpython.git) and added a couple of hacks, as shown in this diff (obviously, update the paths for your own environment):

https://github.com/pvetere/cpython/commit/e291f4e8a656ddf8b75445290d826e6703e5776

Then, from the repo's root, I did the following:

1. Build WASI-enabled Python:
```
Tools/wasm/wasm_build.py wasi compile
```

2. Create the runtime structure in `./pyroot`:
```
cd builddir/wasi && make install && cd ../..
```

3. Pack the runtime libs into the Wasm module.  Run the following command from the root of the repo.  It may take a minute or two:
```
wasi-vfs pack builddir/wasi/python.wasm --mapdir lib::$(pwd)/pyroot -o builddir/wasi/python-with-vfs.wasm
```

4. Now you should be able to run python in Wasm with the VFS, like in the following example.  The `--dir .` option is necessary to give the right capabilities to wasmtime, but the libs are all read from the VFS.
```
% wasmtime run --dir . -- builddir/wasi/python-with-vfs.wasm
Python 3.12.0a0 (heads/main-dirty:32ac98e899, Aug 25 2022, 10:59:15) [Clang 13.0.0 (https://github.com/llvm/llvm-project fd1d8c2f04dde23bee0fb3a7d069 on wasi
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import json
>>>
```

Hope this helps!

**Comment by rjzak** [comment]
Would that still work without `--dir .` ?

**Comment by rjzak** [comment]
I was able to compile with `libwasi_vfs.a`, which is progress! But at the packing step, I got:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: failed to compile the Wasm module

Caused by:
    0: WebAssembly translation error
    1: Invalid input WebAssembly code at offset 3430015: bulk memory support is not enabled', crates/wasi-vfs-cli/src/bin/wasi-vfs.rs:5:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pvetere** [comment]
It doesn't work without '--dir .' for me.  I'm not positive, but I suspect that this might be caused by https://github.com/WebAssembly/WASI/issues/303, and python is trying calling a getcwd() when it starts.

**Comment by rjzak** [comment]
Would it be catastrophic to have `os.getcwd()` (or whichever `getcwd()`) just return "/" on Wasi?

**Comment by pvetere** [comment]
I forgot a step above.  I also had to hack a few lines into wasi-vfs as well.  Then, I used this custom binary on the pack step.  See this diff:

https://github.com/pvetere/wasi-vfs/commit/0a36099e0f1bf86574cebe3db1193ee5da288a03

Maybe this will get you further.

**Comment by rjzak** [comment]
Still not working, same issue with your Wasi-VFS fork.

**Comment by rjzak** [comment]
Do you get an error like this when omitting `--dir .`?

```
Exception ignored error evaluating path:
Traceback (most recent call last):
  File "<frozen getpath>", line 353, in <module>
OSError: [Errno 76] Capabilities insufficient
Fatal Python error: error evaluating path
Python runtime state: core initialized

Current thread 0x00000000 (most recent call first):
  <no Python frame>
Error: failed to execute default function
```

**Comment by pvetere** [comment]
Yes, that's the error I get as well.

**Comment by kateinoigakukun** [comment]
Thank you for your detailed report!

The problems here were:

1. We shouldn't change PREFIX and should use DESTDIR to change the python installation directory
2. VFS doesn't support symlink yet so `path_readlink` should always return `ERRNO_INVAL`

I've also fixed some minor issues that trigger some warnings here: https://github.com/kateinoigakukun/wasi-vfs/pull/6
Could you try again by following the instruction described in the PR?

**Comment by rjzak** [comment]
@kateinoigakukun I still get the error https://github.com/kateinoigakukun/wasi-vfs/issues/5#issuecomment-1227696302, even with the latest `wasi-vfs` code, and recompiling both `libwasi_vfs.a` and `wasi-vfs-cli`. Maybe could you share the VFS-packed binary so I can see if it works with [Enarx](https://github.com/enarx/enarx)?

**Comment by kateinoigakukun** [comment]
@rjzak Hmm, it looks like you didn't enable wasmparser or wasmtime's bulk memory feature in your application. Please review configuration of wasmtime in your loader code.

The compiled binary is too large to upload to GitHub issue... 😅 

<img width="466" alt="Screen Shot 2022-08-27 at 5 20 26" src="https://user-images.githubusercontent.com/11702759/186984742-3aaaf514-e529-4657-a972-f054dce06933.png">

**Comment by rjzak** [comment]
@kateinoigakukun The application is `wasi-vfs` (not wasmtime or any code I wrote) and it doesn't seem to have any features to enable.

**Comment by kateinoigakukun** [comment]
@rjzak Ah sorry, I got it. I think you are using newer version of wasi-sdk, which requires bulk-memory feature and I'm using wasi-sdk 14.0. The root issue is wizer, which is a pre-initialization tool for wasm and this project depends on it, doesn't support the feature for now, so it disables it here: https://github.com/bytecodealliance/wizer/blob/76602d16828648e82720762b83f2ff6f9489ca84/src/lib.rs#L511

We have to add support for the feature to wizer, but could you try with older wasi-sdk for now?

**Comment by rjzak** [comment]
This may be outside the scope of `wasi-vfs`, but I was able to get Python to compile for Wasi with `libwasi_vfs.a`. I now get this error:
```
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000000 (most recent call first):
  <no Python frame>
```

Was the mapping wrong in `--mapdir lib::$(pwd)/pyroot`, or is there something about the embedded filesystem causing a problem for Python?

I didn't try with an older wasi-sdk though...

**Comment by rjzak** [comment]
I did finally get it to work, thank you @kateinoigakukun and @pvetere.
https://drive.google.com/file/d/1ECpCzBkurcrNR-trMF06rJ9kIV4wj6OL/view?usp=sharing
